name = "RequiredInterfaces"
uuid = "97f35ef4-7bc5-4ec1-a41a-dcc69c7308c6"
authors = ["Sukera <Seelengrab@users.noreply.github.com>"]
version = "0.1.0"

[deps]
InteractiveUtils = "b77e0a4c-d291-57a0-90e8-8db25a27a240"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
julia = "1.9"
